language: nodejs

before_script:
  - npm run setup
  - npm install codecov -g
  - npm run build

script:
  - npm test

after_success:
  - codecov --token $CODECOV_TOKEN

deploy:
  - provider: npm
    skip_cleanup: true
    email: $EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
